# --- PHẦN 1: DEPLOYMENT (Cấu hình ứng dụng) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
        - name: movie-app
          image: masterhuthiu/movie-catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: 'mongodb://mongodb:27017/sample_mflix'
            # Cấu hình kết nối Consul để chuẩn bị chạy Frontend
            - name: SPRING_CLOUD_CONSUL_HOST
              value: 'consul'
            - name: SPRING_CLOUD_CONSUL_PORT
              value: '8500'
          # Cấu hình kiểm tra sức khỏe (Probes) nằm trong Container
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 8081
            initialDelaySeconds: 120 # Tăng thêm để Java khởi động kịp
            periodSeconds: 20
---
# --- PHẦN 2: SERVICE (Cổng kết nối nội bộ) ---
apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-service
  namespace: default
spec:
  selector:
    app: movie-catalog-service
  ports:
    - protocol: TCP
      port: 8081 # Cổng của Service
      targetPort: 8081 # Cổng của App
  type: ClusterIP
